name: wids2026_env
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - pip<=25.2
  - pip:
    - mlflow==3.5.1
    - cloudpickle==3.1.1
    - numpy==1.26.4
    - pandas==2.3.3
    - psutil==7.0.0
    - pyarrow==21.0.0
    - scikit-learn==1.7.2
    - scipy==1.15.3

